import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Grid, GridItem, Box, Button } from '@chakra-ui/react'
import FAQ from '../components/FAQ';
import Link from 'next/link';
import Nav from '../components/Nav'


export default function About() {

  return (
    <div className={styles.container}>
      <Head>
        <title>About Fourth Wave</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/FourthWave_Logo_Circle.png"/>
      </Head>
      <Nav/>
      <main className={styles.main}>
        <h1 className={styles.title}>
          About Fourth Wave
        </h1>
        <p className={styles.description}>
          Fourth Wave DAO is a DeFi protocol running on the Polygon Network that helps women in need connect with people that can help.
        </p>
        {/* <p className={styles.descriptionsm}>
          We are growing a network of anonymous Aunties across North America, and will be providing them with the funding they require to support women.
        </p> */}
        <p className={styles.descriptionsm}>
          We will offer education as well as services required for women to stay anonymous while using the internet.
        </p>
        <p className={styles.descriptionsm}>
          Our innovative governance model will be a breath of fresh air to the DeFi ecosystem.
        </p>
        <p className={styles.descriptionsm}>
          Join us as we educate and empower women!
        </p>
        {/* <Grid templateColumns='repeat(5, 1fr)' gap={4} pt="5%" pb='5%'>
          <GridItem colSpan={2} h='100' ><Box boxShadow='xl' p='6' rounded='md' bg='white' w={[100, 200, 300]}>
            <a target="_blank" href="https://medium.com/@alymarguerite/fourth-wave-dao-the-white-paper-dcdce2582a06" rel="noopener noreferrer">
              <Button
                colorScheme="teal"
                variant="ghost"
                bg='purple.100'
                whiteSpace='normal'
                w='100%'
                h='100%'
                p='5%'
                size="lg">The white paper</Button>
            </a>
          </Box>
          </GridItem>
          <GridItem colStart={4} colEnd={6} h='100' w='100%'><Box boxShadow='xl' p='6' rounded='md' bg='white' w={[100, 200, 300]} >
            <FAQ />
          </Box>
          </GridItem>
        </Grid> */}

      </main>

      <footer className={styles.footer}>
        <span className={styles.logo}>
          <Link href="/" passHref>
            <a>
            <Image src="/images/FourthWaveLogo_Transparent.png" alt="Vercel Logo" width={72} height={72} />
            </a>
          </Link>
        </span>
      </footer>
    </div>
  )
}