import React, { useState, useContext } from 'react';
import { Context } from "../context/context";
import Link from 'next/link';
import Nav from '../components/Nav';
import Head from 'next/head';
import Image from 'next/image';
import Wallet from '../components/Wallet';
import styles from '../styles/Home.module.css'

export default function Dash() {

  const { state, dispatch } = useContext(Context);

  const owner = process.env.NEXT_PUBLIC_OWNER
  return (
    <div className={styles.container}>
      <Head>
        <title>Fourth Wave App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/FourthWave_Logo_Circle.png" />
      </Head>
      <Nav />
      <main className={styles.main}>
        <h1 className={styles.title}>
          Time to Pick a Winner!
        </h1>
        <Wallet owner={owner} />
      </main>
      <footer className={styles.footer}>
        <span className={styles.logo}>
          <Link href="/" passHref>
            <a>
              <Image src="/images/FourthWaveLogo_Transparent.png" alt="Vercel Logo" width={72} height={72} />
            </a>
          </Link>
        </span>
      </footer>
    </div>)
}